name: 'Build LaTex Document with Tectonic'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tectonic Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-

      - name: Use wtfjoke/setup-tectonic@v1
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: "latest"

      - name: Install Arial font
        run: |
          sudo apt install ttf-mscorefonts-installer
          sudo fc-cache -f

      - name: Install Texlive-binaries
        run: |
          sudo apt-get install texlive-binaries

      - name: Run Tectonic + makeindex #+ Biber
        run: |
          tectonic --keep-intermediates --reruns 0 thesis.tex
          # biber thesis
          makeindex thesis
          tectonic thesis.tex

      - name: Compress pdf
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
            -dNOPAUSE -dQUIET -dBATCH -sOutputFile=thesis_compressed.pdf thesis.pdf
          echo "Original file size: $(du -sh thesis.pdf)"
          echo "Compressed file size: $(du -sh thesis_compressed.pdf)"
          mv thesis_compressed.pdf thesis.pdf

      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: thesis.pdf
          path: thesis.pdf
