name: 'Build LaTex Document with Tectonic'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEXFN: thesis

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tectonic Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-

      - name: Use wtfjoke/setup-tectonic@v1
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: "latest"

      - name: Install Arial font
        run: |
          # accept the license
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
          sudo fc-cache -f

      - name: Install Texlive-binaries and ghostscript
        run: |
          sudo apt-get install texlive-binaries
          sudo apt-get install ghostscript

      - name: Run Tectonic + makeindex
        run: |
          tectonic --keep-intermediates --reruns 0 ${TEXFN}.tex
          # Make index manually
          makeindex ${TEXFN}
          # Download nomencl.ins manually
          wget http://mirrors.ctan.org/macros/latex/contrib/nomencl/nomencl.ins
          # Produce nomenclature manually
          makeindex ${TEXFN}.nlo -s nomencl.ist -o ${TEXFN}.nls
          tectonic ${TEXFN}.tex

      - name: Compress pdf
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
            -dNOPAUSE -dQUIET -dBATCH -sOutputFile=${TEXFN}_compressed.pdf ${TEXFN}.pdf
          echo "Original file size: $(du -sh ${TEXFN}.pdf)"
          echo "Compressed file size: $(du -sh ${TEXFN}_compressed.pdf)"
          mv ${TEXFN}_compressed.pdf ${TEXFN}.pdf

      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: ${TEXFN}.pdf
          path: ${TEXFN}.pdf
